### ISSUE TITLE
Datapack Load error

### ISSUE THREAD

**Issue by Cynix32** [Mrthomas20121-Mods/Hostile-Neural-Compat#2]
Datapack Load error when loading a world.
log ripped from console: https://pastebin.com/FUUZJ8Ue

Forge 36.2.20
Java 8
MC 1.16.5
HostileNeuralCompat-1.16.5-1.0.1.jar
HostileNeuralNetworks-1.16.5-1.0.1.jar

**Comment by Mrthomas20121** [comment]
i know what's wrong, i'll see what i can do

**Comment by Mrthomas20121** [comment]
i managed to find a fix. expect a release today

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/hostile_neural_compat/files/3567527 fix it
